#define NOTHING 0.000000
#define UP 1.000000
#define RIGHT 2.000000
#define LEFT 3.000000
#define DOWN 4.000000
#define COMMAND 0
#define FAST 30000
#define MEDIUM 45000
#define SLOW 60000
#define TRAINER "trainer"
#define DIRECTORY "directory"
#define SERVER "server address"
#define METHOD "train method"
#define DEFAULT_NAME_TRAINER "trainer"
#define DEFAULT_GAME_DIRECTORY "./"
#define DEFAULT_SERVER_ADDRESS "127.0.0.1"
#define DEFAULT_TRAIN_METHOD "NULL"
#define DEFAULT_THRESHOLDS_PATH "./Configuration/thresholds.json"
#define DEFAULT_KEYS_CONFIG_PATH "./Configuration/keyControlsA.json"
#define KEYBOARD "keyBoard" 
#define FILTER "filter" 
#define GAME "game" 
#define GAME_SCORE "score"
#define GAME_STEPS "steps"
#define GAME_KEYS "keys"
#define JSONFILE "newbie_configuration.json"
#define METHOD_RAM "ram"
#define METHOD_FULLRAM "fullram"
#define METHOD_RGB "rgb"
#define THRESHOLDS "thresholds"
#define INDENTATION 4
#define WIDTH "Width"
#define HEIGTH "Heigth"
#define MAP_WIDTH "Map_Width"
#define MAP_HEIGTH "Map_Heigth"
#define RESIZE_X "Resize_X"
#define RESIZE_Y "Resize_Y"
#define PATH_X "Path_X"
#define PATH_Y "Path_Y"
#define REPLACE_EXCEPTION "Replace_Exception"
#define POSITION_X 'X'
#define POSITION_Y 'Y'
#define MAP_CHAR_SPACE ' '
#define MAP_CHAR_PACMAN 'P'
#define MAP_CHAR_SCORE 'S'
#define MAP_CHAR_PACMAN_SCORE 'V'
#define MAP_CHAR_PILL 'U'
#define MAP_CHAR_WALL 'M'
#define MAP_CHAR_WAY 'C'
#define MAP_CHAR_GHOST1 '1'
#define MAP_CHAR_GHOST2 '2'
#define MAP_CHAR_GHOST3 '3'
#define MAP_CHAR_GHOST4 '4'
#define MAP_CHAR_FRUIT 'O'
#define MAP_CHAR_GHOST_EAT 'E'
#define MAP_CHAR_GHOST_TIME_OUT_EAT 'N'
#define MAP_CHAR_DEFAULT 'X'
#define DEFAULT_WIDTH 160
#define DEFAULT_HEIGTH 210
#define DEFAULT_RESIZE 1
#define DEFAULT_PATH 0
#define DEFAULT_EXCEPTION 0
#define COLOR_SPACE "Color_Space"
#define COLOR_WALL "Color_Wall"
#define COLOR_WAY "Color_Way"
#define COLOR_PACMAN_SCORE "Color_Pacman_Score"
#define COLOR_PACMAN "Color_Pacman"
#define COLOR_SCORE "Color_Score"
#define COLOR_FRUIT "Color_Fruit"
#define COLOR_GHOST1 "Color_Ghost1"
#define COLOR_GHOST2 "Color_Ghost2"
#define COLOR_GHOST3 "Color_Ghost3"
#define COLOR_GHOST4 "Color_Ghost4"
#define COLOR_GHOST_EAT "Color_GhostEat"
#define COLOR_GHOST_TIME_OUT "Color_GhostTimeOuT"
#define COLOR_RED 0
#define COLOR_GREEN 1
#define COLOR_BLUE 2 
#define DATA_LENGTH 128
#define RGB_PATH "rgb"
#define MATCH_JSON "match.json"
#define ANSI_COLOR_RED "\x1b[31m"
#define ANSI_COLOR_RESET   "\x1b[0m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define PORT 5000
#define POSITION_X_GHOST_CLYDE_RAM 6
#define POSITION_Y_GHOST_CLYDE_RAM 12
#define POSITION_X_GHOST_INKY_RAM 7
#define POSITION_Y_GHOST_INKY_RAM 13
#define POSITION_X_GHOST_PINKY_RAM 8
#define POSITION_Y_GHOST_PINKY_RAM 14
#define POSITION_X_GHOST_BLINKY_RAM 9
#define POSITION_Y_GHOST_BLINKY_RAM 15
#define POSITION_X_PACMAN_RAM 10
#define POSITION_Y_PACMAN_RAM 16
#define DEFAULT_MAX 0
#define DEFAULT_MIN 9999
#define MOVE_ONE_POSITION 1
#define MOVE_TWO_POSITION 2
#define MOVE_THREE_POSITION 3
#define DEFAULT_POSITION_X "X"
#define DEFAULT_POSITION_Y "Y"
#define NEURAL_NETWORK_SAVE_FILE "/home/ubuntu/Desktop/prueba/neural.json"
#define DEFAULT_POSITION_PACMAN_X "PX"
#define DEFAULT_POSITION_PACMAN_Y "PY"
#define DEFAULT_POSITION_GHOST1_X "1X"
#define DEFAULT_POSITION_GHOST1_Y "1Y"
#define DEFAULT_POSITION_GHOST2_X "2X"
#define DEFAULT_POSITION_GHOST2_Y "2Y"
#define DEFAULT_POSITION_GHOST3_X "3X"
#define DEFAULT_POSITION_GHOST3_Y "3Y"
#define DEFAULT_POSITION_GHOST4_X "4X"
#define DEFAULT_POSITION_GHOST4_Y "4Y"
#define NUMBER_BYTES 128
#define RANGE_LIMIT_BYTES_FILTER 10
#define FILTER_BYTES_SAVE_FILE "filterBytes.json"
#define BYTES "Bytes"
#define QUANTITYLAYERSHIDDEN "quantityLayersHidden"
#define HIDDENNODES "hiddenNodes"
#define FIRST_STEP_VALUE 0
#define FIRST_BYTE_RANGE 0
#define LAST_BYTE_RANGE 1
#define LAST_BYTE_RANGE 1
#define FILTER_BY_COLUMNS "filter_by_columns"
#define FILTER_COLUMNS "columns"
#define FILTER_COLUMNS_ONLY_THIS "only_this"
#define FILTER_COLUMNS_EXCLUDE_THIS "exclude_this"
#define FILTER_EXCLUDE_CONSTANTS "exclude_constants"
#define FILTER_BY_VALUE "filter_by_value"
#define FILTER_BY_VALUE_VALUE "value"
#define FILTER_OPERATION "operation"
#define FILTER_BY_VALUE_OPERATION_GREATER_EQUAL "greater_equal"
#define FILTER_BY_VALUE_OPERATION_LESS_EQUAL "less_equal"
#define FILTER_BY_RANGES_VALUES "filter_by_ranges_values"
#define FILTER_BY_RANGES_VALUES_RANGES "ranges"
#define FILTER_BY_RANGES_VALUES_MIN "min"
#define FILTER_BY_RANGES_VALUES_MAX "max"
#define FILTER_TOP_CHANGE_COLUMNS "filter_top_change_columns"
#define FILTER_TIMES_COLUMN_CHANGE_VALUE "filter_times_column_change_value"
#define FIRST_STEP_BYTES 0
